---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: loadbalancer
  region: us-east-1
  version: "1.28"
  tags:
    env: loadbalancer

# privateCluster:
#   enabled: true

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true

vpc:
  id: <VPC-ID>
  subnets:
    private:
      us-east-1a:
        id: <SUBNET-ID>
      us-east-1b:
        id: <SUBNET-ID>
      us-east-1c:
        id: <SUBNET-ID>

managedNodeGroups:
  - name: default
    privateNetworking: true
    instanceType: t3a.medium
    spot: true
    minSize: 1
    desiredCapacity: 1
    maxSize: 3
    volumeSize: 20
