---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: practica5
  region: us-east-1
  version: "1.28"
  tags:
    env: practica5

# privateCluster:
#   enabled: true

iam:
  withOIDC: true

vpc:
  id: vpc-0489230161cb74bd3
  subnets:
    private:
      us-east-1a:
        id: subnet-022792d4958653f8b
      us-east-1b:
        id: subnet-034147412ef94462a
      us-east-1c:
        id: subnet-07828c9f7252927de

managedNodeGroups:
  - name: large
    privateNetworking: true
    instanceType: t3a.large
    spot: true
    minSize: 1
    desiredCapacity: 1
    maxSize: 1
    volumeSize: 20

  - name: medium
    privateNetworking: true
    instanceType: t3a.medium
    spot: true
    minSize: 1
    desiredCapacity: 1
    maxSize: 3
    volumeSize: 20
