---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: practica5
  region: us-east-1
  version: "1.24"
  tags:
    env: practica5

# privateCluster:
#   enabled: true

iam:
  withOIDC: true

vpc:
  id: <VPC_ID>
  subnets:
    private:
      us-east-1a:
        id: <SUBNET_ID>
      us-east-1b:
        id: <SUBNET_ID>
      us-east-1c:
        id: <SUBNET_ID>

managedNodeGroups:
  - name: large
    privateNetworking: true
    instanceType: t3a.large
    spot: true
    minSize: 1
    desiredCapacity: 1
    maxSize: 1
    volumeSize: 20

  - name: medium
    privateNetworking: true
    instanceType: t3a.medium
    spot: true
    minSize: 1
    desiredCapacity: 1
    maxSize: 3
    volumeSize: 20
