apiVersion: apps/v1
kind: Deployment

metadata:
  name: deploy-practica-1
  namespace: practica
  labels:
    lab: uno

spec:
  replicas: 3

  template:
    metadata:
      name: app-uno
      labels:
        lab: uno

    spec:
      containers:
        - image: cachac/kubelabs:3.0
          name: practica
          ports:
            - containerPort: 8080
          resources:

  selector:
    matchLabels:
      lab: uno

# kubectl create namespace practica
# kubectl get pods -n practica
# k expose -n practica deployment deploy-practica-1 --name practica --port 8080
# k exec test2 -- curl svc-practica.practica.svc.cluster.local:8080
