apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: php-apache
  name: php-apache
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-apache
  strategy:
    rollingUpdate:
      maxSurge: 75%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - image: us.gcr.io/k8s-artifacts-prod/hpa-example
        imagePullPolicy: Always
        name: hpa-example
        resources:
          limits:
            memory: 1000Mi
            cpu: 500m
          requests:
            memory: 700Mi
            cpu: 100m

      terminationGracePeriodSeconds: 10
